M48
; DRILL file {KiCad 9.0.6} date 2025-11-09T15:26:29+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-09T15:26:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X6.0364Y-2.0583
X6.2274Y-2.0583
T2
X6.0246Y-1.939
X6.2392Y-1.939
M30
