name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable # Or specify a specific version that you know works with your project
        override: true
        target: thumbv6m-none-eabi # Add this line to specify the target architecture
    - name: Add target for Rust
      run: rustup target add thumbv6m-none-eabi
    - name: Build
      run: cargo build --target=thumbv6m-none-eabi --verbose
    # Optionally, uncomment to run tests
    # - name: Run tests
    #   run: cargo test --target=thumbv6m-none-eabi --verbose