name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: thumbv6m-none-eabi
    - name: Add Rust target
      run: rustup target add thumbv6m-none-eabi
    - name: Build
      run: cargo build --target thumbv6m-none-eabi --verbose